# Book settings
title: Callysto Curriculum Notebooks
author: Callysto.ca (A joint project of Cybera Inc and the Pacific Institute for the Mathematical Sciences)
logo: CallystoLogo.png

latex:
  latex_documents:
    targetname: book.tex

execute:
  execute_notebooks: 'auto'
  exclude_patterns:
    - 'introduction-to-python.ipynb'
    - 'electrical-conductivity.ipynb'

repository:
  url : https://github.com/callysto/curriculum-notebooks

launch_buttons:
  notebook_interface : classic  
  binderhub_url : https://mybinder.org 
  jupyterhub_url : "https://hub.callysto.ca"  
  thebelab                  : false  

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

parse:
  myst_extended_syntax: true



